### ISSUE TITLE
Wrong month number

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo-api#42]
The month require a +1, ref [https://www.w3schools.com/jsref/jsref_getmonth.asp](https://www.w3schools.com/jsref/jsref_getmonth.asp)

> getMonth() returns the month (0 to 11) of a date.
>January =0, February = 1, ... (see below):

https://github.com/ta-vivo/ta-vivo-api/blob/693f5b3a4993ec064c8a2d128afc57106b23d10b/src/utils/time.js#L9

**Comment by Jadhielv** [comment]
@itsalb3rt If you like, you can assign me this issue.

**Comment by itsalb3rt** [comment]
> @itsalb3rt If you like, you can assign me this issue.

Sure

**Comment by itsalb3rt** [comment]
I made a change, this is a critical issue
