### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo-api#67]
**Is your feature request related to a problem? Please describe.**
Update dependencies of the API. Remember, the API provide all the necessary to run in local.

**Describe the solution you'd like**
Use the command of yarn to update the dependencies 

```bash
yarn upgrade-interactive
```

**Describe alternatives you've considered**
None

**Comment by inomag** [comment]
Hi, can I take this issue

**Comment by itsalb3rt** [comment]
Sure, thanks!

**Comment by Jadhielv** [comment]
Hi @inomag, if you're busy, I can take this issue. Please, just let me know.

**Comment by inomag** [comment]
@Jadhielv Yes sure.

**Comment by Jadhielv** [comment]
@itsalb3rt I can take this issue.

**Comment by itsalb3rt** [comment]
Sure, go.
