### ISSUE TITLE
Add a feature on the history logs to allow download in csv

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo-api#87]
**Description**

Add a feature on the history logs to allow download in csv [Backend documentation](https://documentation.tavivo.do/back-end/)

**How to do**

- The first step is checked the following route https://github.com/ta-vivo/ta-vivo-api/blob/1f70ef899799f512a768fbc9ea5f4e039bd93cf3/src/routes/Check.js#L9
- The proposal is creating other route like the `router.get('/:id/logs')` but with a extra parameter to indicate the file download, for example `router.get('/:id/logs/download')`
- The response need the header `"Content-Type", "text/csv"`

**Comment by bernestdev** [comment]
I can work on this. Please assign it to me

**Comment by itsalb3rt** [comment]
Done https://github.com/ta-vivo/ta-vivo-api/pull/91
