### ISSUE TITLE
Slack integration acts as if it is mandatory

### ISSUE THREAD

**Issue by bernestdev** [ta-vivo/ta-vivo-api#89]
**Describe the bug**
I'm trying to start the API on development mode and I can't get it started because I'm missing valid environment variables for the Slack integration

**To Reproduce**
1. Delete all variables refering to the Slack integration from the `.env` file
2. Run the API with `yarn dev'
3. The app will crash

**Expected behavior**
Deleting the variables should allow the API to run as the integration should not be mandatory

**Screenshots**
![image](https://github.com/ta-vivo/ta-vivo-api/assets/12449517/650c5885-35d4-4730-a189-8c6b4ce71b44)

![image](https://github.com/ta-vivo/ta-vivo-api/assets/12449517/3530a2db-ec15-42fc-a87e-3659f6476d1f)

**Possible solutions**
A solution would be to check for the definition of the needed env variables before trying to initialize the SlackService. Check the screenshot below:

Before the fix
![image](https://github.com/ta-vivo/ta-vivo-api/assets/12449517/efc1803d-3ce5-4394-a0f3-d393a76ecf62)

After the fix
![image](https://github.com/ta-vivo/ta-vivo-api/assets/12449517/bfaa7823-9b30-4c96-800b-cfd45339b86f)

Here we have a conditional to check for the needed variables before trying to initialize the app. The code above works for both scenarios:
1. When the variables are not defined at all
2. When the variables are in the `.env` file but have no value.

I can apply the fix and upload the changes if you approve this solution. Please let me know.

**Comment by itsalb3rt** [comment]
Thanks @bernestdev please create a Pull Request to merge this 🙌
