### ISSUE TITLE
Telegram integration acts as if it is mandatory

### ISSUE THREAD

**Issue by bernestdev** [ta-vivo/ta-vivo-api#90]
**Describe the bug**
The app would throw many `polling_error` when trying to run the API without the `TELEGRAM_BOT_TOKEN` variable defined. The error does not block the API from running but quickly fills the console with error logs making it hard to debug other issues.

**To Reproduce**
1. Delete the variable (or leave empty) `TELEGRAM_BOT_TOKEN` from your `.env` file.
2. Run the app with `yarn dev` and check the `polling_error` being constantly logged on the console.

**Expected behavior**
The API should run with not errors when no Telegram integration is defined as integrations should be optional.

**Screenshots**
Error being thrown in the console
![image](https://github.com/ta-vivo/ta-vivo-api/assets/12449517/4fcba0ce-1dbe-49d1-b209-be9ed8dc96bf)

**Suggested solution**
Make sure to check if the env variable `TELEGRAM_BOT_TOKEN` exists before trying to initialize the service. Check screenshot below

Before fix:
![image](https://github.com/ta-vivo/ta-vivo-api/assets/12449517/8ddc4471-f8c2-46f5-a9b4-006bca4880b7)

After fix:
![image](https://github.com/ta-vivo/ta-vivo-api/assets/12449517/a8074c52-f026-4df6-a41a-f4754cb13bb6)

This works for both cases:
1. The variable is not defined at all
2. The variable is defined on the `.env` file but is empty

Please let me know if you agree with this fix and I can apply it.

**Comment by itsalb3rt** [comment]
Thanks @bernestdev please create a Pull Request to merge 🙌
